CREATE TABLE NVB_DOCS_OWNER.INVESTMENT_DOCUMENT
(
    ID                   NUMBER(12)      NOT NULL PRIMARY KEY,
    UUID                 VARCHAR2(36)    NOT NULL,
    NAME                 VARCHAR2(50),
    PRODUCT_TYPE         VARCHAR2(30)    NOT NULL,
    PROCESS_TYPE         VARCHAR2(30)    NOT NULL,
    CUSTOMER             VARCHAR2(128)   NOT NULL,
    EMPLOYEE             VARCHAR2(10),
    AGREEMENT_ID         VARCHAR2(40),
    EXTERNAL_ID          VARCHAR2(36)    NOT NULL,
    TYPE                 VARCHAR2(30)    NOT NULL,
    STATUS               VARCHAR2(12)    NOT NULL,
    SIGNING_STATUS       VARCHAR2(12)    NOT NULL,
    DOCUMENT_CONTENT_ID  NUMBER(12),
    CREATED_AT           TIMESTAMP       NOT NULL,
    UPDATED_ON           TIMESTAMP       NOT NULL,
    EXPIRES_ON           TIMESTAMP,
    PARENT_DOSSIER_ID    NUMBER(12)
);

CREATE SEQUENCE NVB_DOCS_OWNER.INVESTMENT_DOCUMENT_SEQ START WITH 1 INCREMENT BY 1;
